services:
  promptlayer-proxy-q:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: promptlayer-proxy
    restart: always
    ports:
      - "5437:3000"
    environment:
      - LOG_LEVEL=info   
    volumes:
      - ./logs:/app/logs